#!/usr/bin/env python3
"""verify_all.py — full check registry for the Paper 2 companion repo.

This is the command printed in Technical Supplement I (v5.4),
"Computational verification": running

    python verify_all.py

from the repository root runs the full 20-check registry bundled with
this repo — including check_T_field (the ordered-tuple scan, gauge.py
path) and check_L_F6_not_from_EC (the canonical full-system waterfall,
ec_inventory_reading.py) — with no dependencies beyond the Python
standard library.

VERSION LOCK: numerical kernel at canonical commit 5bc6193
(v24.3.423, 2026-07-14; bank 3912, native verify_all --bank-audit
3912/3912 gap 0); later engine commits are count-neutral corrigenda
(trail in the release manifest), and check functions are vendored at
the corrigenda-trail head.

Usage:
    python verify_all.py                 # run all 20 checks
    python verify_all.py --paper2-core   # fast path: the 6 classification-core checks
    python verify_all.py --check NAME    # run a single check by name
    python verify_all.py --verbose       # per-check detail

The scan's audit files (scan_inputs.json, scan_outputs.csv,
filter_waterfall.csv, near_misses.csv, kill_index.csv,
certificate.sha256) are generated by the canonical executable:

    python fermion_scan_standalone.py --emit-audit
"""

import sys
import argparse
import time

from apf.bank import REGISTRY, EXPECTED_CHECK_COUNT, get_check, run_all

VERSION_LOCK = {
    'codebase': 'v24.3.423',
    'numerical_kernel_commit': '5bc6193',   # scan numbers locked here;
    # later engine commits are count-neutral corrigenda (trail in
    # fermion_scan_standalone.VERSION_LOCK / release_audit/scan_inputs.json)
    'bank': 3912,
    'paper_main': 'Paper_2_Structure_of_Admissible_Physics_v7.3',
    'supplement_I': 'Paper_2_Structure_of_Admissible_Physics_Supplement_v5.4',
    'supplement_II': 'Paper_2_Foundational_Gauge_Program_Supplement_v1.0',
}

# The classification core: the checks that carry the paper's principal
# claim (the conditional 1,680-template theorem and its gauge template).
PAPER2_CORE = [
    'check_Theorem_R',
    'check_L_gauge_template_uniqueness',
    'check_L_cost_gauge',
    'check_T_field',
    'check_L_F6_not_from_EC',
    'check_L_count',
]


def _run(names, verbose=False):
    results = []
    for name in names:
        fn = REGISTRY[name]
        try:
            r = fn()
            if not isinstance(r, dict):
                r = {'name': name, 'passed': bool(r)}
            r.setdefault('name', name)
            r.setdefault('passed', True)
        except Exception as e:  # noqa: BLE001 — a check raising is a FAIL
            r = {'name': name, 'passed': False,
                 'error': f'{type(e).__name__}: {e}'}
        status = 'PASS' if r['passed'] else 'FAIL'
        print(f'  {status}  {name}')
        if verbose and r.get('key_result'):
            print(f'        {r["key_result"]}')
        results.append(r)
    return results


def main():
    p = argparse.ArgumentParser(description='Verify the Paper 2 check registry.')
    p.add_argument('--paper2-core', action='store_true',
                   help='fast path: run only the 6 classification-core checks')
    p.add_argument('--check', '-c', default=None,
                   help='run a single check by name')
    p.add_argument('--verbose', '-v', action='store_true')
    args = p.parse_args()

    print('=' * 72)
    print('  APF Paper 2 — The Structure of Admissible Physics')
    print(f'  Version-locked release: canonical codebase '
          f'{VERSION_LOCK["codebase"]} (numerical kernel '
          f'{VERSION_LOCK["numerical_kernel_commit"]}, bank '
          f'{VERSION_LOCK["bank"]}; count-neutral corrigenda trail in '
          f'the release manifest)')
    print(f'  Registry: {len(REGISTRY)} checks '
          f'(expected {EXPECTED_CHECK_COUNT})')
    print('=' * 72)

    if len(REGISTRY) != EXPECTED_CHECK_COUNT:
        print(f'  ERROR: registry size {len(REGISTRY)} != '
              f'expected {EXPECTED_CHECK_COUNT}')
        sys.exit(2)

    if args.check:
        try:
            get_check(args.check)
        except KeyError:
            print(f'  ERROR: no check named {args.check!r}.')
            print(f'  Available: {sorted(REGISTRY)}')
            sys.exit(1)
        names = [args.check]
    elif args.paper2_core:
        print('  Mode: --paper2-core '
              f'({len(PAPER2_CORE)} classification-core checks)')
        names = PAPER2_CORE
    else:
        names = list(REGISTRY)

    t0 = time.time()
    results = _run(names, verbose=args.verbose)
    dt = time.time() - t0

    passed = sum(1 for r in results if r['passed'])
    failed = len(results) - passed
    print('-' * 72)
    print(f'  {passed} passed, {failed} failed, {len(results)} total '
          f'— {dt:.2f}s')

    if args.paper2_core and failed == 0:
        print('  Canonical waterfall (full-system F6): '
              '1680 -> 348 -> 324 -> 24 -> 12 -> 10 -> 5 -> 1 (SM @ 45)')
        print('  F6 predicate triple on the 12 F1-F5 survivors '
              '(pre/post CPT): canonical 10/5 | spectator 8/4 | uniform 4/2 '
              '— winner invariant at 45')
        print('  Audit bundle: python fermion_scan_standalone.py --emit-audit '
              '(regenerates release_audit/ byte-identically)')
    if failed:
        for r in results:
            if not r['passed']:
                print(f'  FAILED {r["name"]}: {r.get("error", "no detail")}')
        sys.exit(1)
    sys.exit(0)


if __name__ == '__main__':
    main()
